### ISSUE TITLE
Is TIME_BEFORE_NEWBIE_TIME too short?

### ISSUE THREAD

**Issue by hemberger** [smrealms/smr#140]
Setting aside the fact that this was probably supposed to be called `TIME_BEFORE_NEWBIE_TURN`... ;)

This is currently set to 1 hour. If no one accesses the server, we assume the server went down and give everyone (who is not on a planet) a newbie turn. Perhaps this doesn't matter too much, since if no one is playing for one hour, then everyone is likely to be on a planet or in fed anyway; otherwise, if someone is moving and the server goes down for over an hour, then they are given the safety of a newbie turn.

With the reduced game population, I was just wondering if this 1 hour still makes sense.

**Comment by Page-** [comment]
I think it makes sense, because the idea is that it should match how long the game has to be unavailable for in order for a newbie turn to be granted (because you can't expect people to wait around indefinitely to log back in once the server comes back online) - setting it to 12 hours for instance would mean that the game could go down for 6 hours, I have to go to bed, and the game comes back whilst I'm asleep and I wake up in a pod - not exactly a pleasant experience.

**Comment by hemberger** [comment]
Sounds reasonable to me!
