### ISSUE TITLE
InternalServerError in lib/Login/loginSmarty.php

### ISSUE THREAD

**Issue by MichaelKunze** [smrealms/smr#19]
The line

 $gameNews[] = array('Date' => date(DEFAULT_DATE_DATE_SHORT,$db->getField('time')), 'Time' => date(DEFAULT_DATE_TIME_SHORT,$db->getField('time')), 'Message' => bbifyMessage($db->getField('news_message')));

gives a 500 error on login. has been commented for the time being.

**Comment by hemberger** [comment]
Since we now understand this issue to be related to incomplete server updates (i.e. updating libraries but not restarting services), can we close this? Or should we wait until the server is using the docker infrastructure, which will _enforce_ that software is only updated when services are updated?

**Comment by MichaelKunze** [comment]
To be precise the nginx has been restarted a couple of times to solve the issue. If it does not happen after rebooting the server close the issue for good. No need to wait.

**Comment by hemberger** [comment]
Rebooting the server resolved this issue. We'll close this now. Thanks!
